"""phase5 keyword search tsvector

Revision ID: 9bf464844c80
Revises: 9da91cdd6bb1
Create Date: 2026-08-13 22:43:37.756023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9bf464844c80'
down_revision: Union[str, None] = '9da91cdd6bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('searchable_content', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=True))
    op.create_index('ix_document_chunks_searchable_content_gin', 'document_chunks', ['searchable_content'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_chunks_searchable_content_gin', table_name='document_chunks', postgresql_using='gin')
    op.drop_column('document_chunks', 'searchable_content')
    # ### end Alembic commands ###
