"""phase3 document ingestion fields

Revision ID: 9da91cdd6bb1
Revises: d139fb9f4697
Create Date: 2026-08-13 20:39:47.093591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da91cdd6bb1'
down_revision: Union[str, None] = 'd139fb9f4697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_filename', sa.String(length=1024), nullable=False))
    op.add_column('documents', sa.Column('mime_type', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.BigInteger(), nullable=False))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processed_at')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'original_filename')
    # ### end Alembic commands ###
